<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.pikatimer</groupId>
    <artifactId>pikatimer-tests</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.13.2</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-base</artifactId>
            <version>17.0.2</version>
            <classifier>linux</classifier>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>javax.persistence</groupId>
            <artifactId>javax.persistence-api</artifactId>
            <version>2.2</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.hibernate</groupId>
            <artifactId>hibernate-core</artifactId>
            <version>5.6.15.Final</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>build-helper-maven-plugin</artifactId>
                <version>3.6.0</version>
                <executions>
                    <execution>
                        <id>add-test-sources</id>
                        <phase>generate-test-sources</phase>
                        <goals>
                            <goal>add-test-source</goal>
                        </goals>
                        <configuration>
                            <sources>
                                <source>${project.basedir}/src</source>
                                <source>${project.basedir}/test</source>
                            </sources>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.11.0</version>
                <configuration>
                    <testIncludes>
                        <testInclude>com/pikatimer/race/AwardCategory.java</testInclude>
                        <testInclude>com/pikatimer/race/AwardCategoryType.java</testInclude>
                        <testInclude>com/pikatimer/race/AwardDepthType.java</testInclude>
                        <testInclude>com/pikatimer/race/AwardDepth.java</testInclude>
                        <testInclude>com/pikatimer/race/AwardFilter.java</testInclude>
                        <testInclude>com/pikatimer/race/AwardWinner.java</testInclude>
                        <testInclude>com/pikatimer/util/DurationFormatter.java</testInclude>
                        <testInclude>com/pikatimer/util/DurationParser.java</testInclude>
                        <testInclude>com/pikatimer/util/AlphanumericComparator.java</testInclude>
                        <testInclude>com/pikatimer/race/AwardCategoryAgeGroupWinnersTest.java</testInclude>
                        <testInclude>com/pikatimer/race/Race.java</testInclude>
                        <testInclude>com/pikatimer/race/RaceAwards.java</testInclude>
                        <testInclude>com/pikatimer/race/SexGroups.java</testInclude>
                        <testInclude>com/pikatimer/race/AgeGroups.java</testInclude>
                        <testInclude>com/pikatimer/participant/Participant.java</testInclude>
                        <testInclude>com/pikatimer/participant/ParticipantDAO.java</testInclude>
                        <testInclude>com/pikatimer/results/ProcessedResult.java</testInclude>
                        <testInclude>com/pikatimer/results/ResultsDAO.java</testInclude>
                        <testInclude>com/pikatimer/timing/Split.java</testInclude>
                    </testIncludes>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
